tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "sambadevi/powerlevel9k"
brew "ansiweather"
brew "bat"
brew "ctags"
brew "htop"
brew "jenv"
brew "mas"
brew "node"
brew "pinentry-mac"
brew "rbenv"
brew "thefuck"
brew "tmux"
brew "sambadevi/powerlevel9k/powerlevel9k"
cask "alfred"
cask "bettertouchtool"
cask "caprine"
cask "discord"
cask "docker"
cask "firefox"
cask "font-hack-nerd-font"
cask "github"
cask "java"
cask "lastpass"
cask "mysqlworkbench"
cask "postman"
cask "robo-3t"
cask "spotify"
cask "zoomus"
mas "Downcast", id: 668429425
mas "Irvue", id: 1039633667
mas "LastPass", id: 926036361
mas "Push To Talk", id: 547067197
mas "Skitch", id: 425955336
